"""Create doctor table

Revision ID: 52807d8a3b0b
Revises: 66c518ed85c5
Create Date: 2026-07-06 12:25:15.970620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52807d8a3b0b'
down_revision = '66c518ed85c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('doctor_code', sa.String(length=20), nullable=False),
    sa.Column('qualification', sa.String(length=200), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('consultation_fee', sa.Float(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('available_days', sa.String(length=100), nullable=True),
    sa.Column('available_time', sa.String(length=100), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_code'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctors')
    # ### end Alembic commands ###
