"""Add appointment fields

Revision ID: 8c50c3e4cb11
Revises: 3df00857ede2
Create Date: 2026-07-10 11:15:59.650912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c50c3e4cb11'
down_revision = '3df00857ede2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_type', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('token_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fee', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('fee')
        batch_op.drop_column('token_number')
        batch_op.drop_column('visit_type')

    # ### end Alembic commands ###
